CREATE TABLE DEPARTAMENTO (
	ID 		NUMBER(10) NOT NULL,
	NOMBRE VARCHAR2(100) NOT NULL,
	FECHA DATE NOT NULL	
);
ALTER TABLE DEPARTAMENTO ADD(
	CONSTRAINT departamento_pk PRIMARY KEY(ID)
);
CREATE SEQUENCE departamento_seq START WITH 1;

CREATE OR REPLACE TRIGGER departamento_bir
	BEFORE INSERT ON DEPARTAMENTO
	FOR EACH ROW	
	BEGIN
		SELECT departamento_seq.NEXTVAL
		INTO :new.id
		FROM dual;
	END;
INSERT INTO DEPARTAMENTO (NOMBRE, FECHA) VALUES ('Programacion', SYSDATE);
INSERT INTO DEPARTAMENTO (NOMBRE, FECHA) VALUES ('Diseño', '1/2/2019');
INSERT INTO DEPARTAMENTO (NOMBRE, FECHA) VALUES ('Marketing', '5/1/2019');
INSERT INTO DEPARTAMENTO (NOMBRE, FECHA) VALUES ('Direccion', '20/1/2019');

ALTER TABLE USUARIO ADD DEPART_PRINCIPAL NUMBER(10) DEFAULT 1 NOT NULL;

UPDATE USUARIO SET DEPART_PRINCIPAL = ROUND(dbms_random.value(1, 4));

SELECT *  FROM usuario U JOIN DEPARTAMENTO D
	ON u.DEPART_PRINCIPAL = d.id;
	
SELECT *  FROM usuario U JOIN DEPARTAMENTO D
	ON u.DEPART_PRINCIPAL = d.id WHERE D.Nombre = 'Programacion';

ALTER TABLE usuario DROP COLUMN DEPART_PRINCIPAL;

CREATE TABLE USU_DEPT (
	ID_USU NUMBER(10) NOT NULL,
	ID_DEPT NUMBER(10) NOT NULL
);
ALTER TABLE USU_DEPT
	add constraint FK_USU_DEPT_usu
	FOREIGN KEY (ID_USU) REFERENCES USUARIO(ID);
	
ALTER TABLE USU_DEPT
	add constraint FK_USU_DEPT_departamento
	FOREIGN KEY (ID_DEPT) REFERENCES DEPARTAMENTO(ID);

ALTER TABLE USU_DEPT ADD(
	CONSTRAINT a_dept_usu_pk PRIMARY KEY(ID_USU, ID_DEPT)
);
INSERT INTO USU_DEPT(ID_USU, ID_DEPT) 
	VALUES (ROUND(dbms_random.value(1, (SELECT COUNT(*) FROM USUARIO))), 
			ROUND(dbms_random.value(1, 4)));

select U.NOMBRE, d.nombre from usuario  u
	JOIN USU_DEPT UD ON U.id = UD.ID_USU
	JOIN DEPARTAMENTO d ON UD.ID_DEPT = D.id
		WHERE d.nombre = 'Programacion';

/* select U.NOMBRE, d.nombre from usuario  u
	JOIN USU_DEPT UD USING (UD.ID_USU)
	JOIN DEPARTAMENTO d USING (d.id)
		WHERE d.nombre = 'Programacion';*/





